### ISSUE TITLE
Does this actually work?

### ISSUE THREAD

**Issue by cmalven** [sublimelsp/LSP-stylelint#2]
I'd find this very useful, but unlike all of the other Sublime LSP languages I've tried so far, this is the only one that doesn't work and doesn't even error. Is there an npm library I need to install globally?

I'd love to use this, but I'm at a loss for why it isn't working and I don't want to waste time messing with it if it isn't quite ready for primetime yet.

If it _shoud_ be working, anything I can look for to figure out why it isn't? Thanks!

**Comment by rchl** [comment]
- Does it even start up? Do you see `lsp-stylelint` in the status bar?
 - What extension does the file you are trying it on has?
 - https://lsp.readthedocs.io/en/latest/troubleshooting/

**Comment by rchl** [comment]
I just found an issue related to ST3 + SCSS so I'll fix that.

**Comment by rchl** [comment]
Actually, for CSS it was already not triggering in ST3. :)
The problem was with the wrong syntaxes being assigned. In ST4 those don't matter anymore so it worked there.

**Comment by cmalven** [comment]
@rchl Thanks for responding. I tried with SCSS and CSS, both in ST3. No signs of anything happening in the status bar either, but sounds like you're on top of it.

Let me know if there's anything I can do to help, and thanks for your work on this.

**Comment by cmalven** [comment]
BTW, just tried it again with 1.0.1 and its working!

**Comment by peterlobster** [comment]
I don't think it's working, at least for me. It says it `intializes` but it doesn't give any other than `Code Action` that doesn't seem to work.

**Comment by predragnikolic** [comment]
@peterlobster try opening a new issue, and make sure to write which sublime text version you are using and paste your server logs in the issue(see this [page](https://lsp.readthedocs.io/en/latest/troubleshooting/) on how to enable logging )
