### ISSUE TITLE
Suggestions no appearing when writing `.stylelintrc`

### ISSUE THREAD

**Issue by peterlobster** [sublimelsp/LSP-stylelint#29]
When using the upstream VSCode `stylelint` extension, when editing `.stytlelintrc`, you type `"`, you're given the list of rules to chose from. It would be nice to have that feature for Sublime as well. I could find a way of enabling it, if it's already there.

**Comment by rwols** [comment]
Doesn't LSP-json provide completions for `.stylelintrc`? It shows up in https://www.schemastore.org/json/

**Comment by peterlobster** [comment]
@rwols Yes, thank you. That addressed my problem.
