### ISSUE TITLE
Not picking up Prettier integration

### ISSUE THREAD

**Issue by ran-dall** [sublimelsp/LSP-stylelint#30]
I'm using the OFFICAL Prettier StyleLint integration (https://github.com/prettier/stylelint-prettier), and it's not picking up anything on Sublime. On VSCode, it seems to pick up just fine.

@rchl I'll push a simple update to the same repo (https://github.com/Mountain-Cabins-Utah/Website) we're using for the #28 for your convenience. It should have everything set up correctly for you to test with VSCode (or VSCodium) and Sublime. In particular, I'm using the `styles/mixins.css` file to test.

VSCodium
![image](https://user-images.githubusercontent.com/17261190/168477547-d8a144b9-db63-433d-a299-b3e3d9823b25.png)

Sublim Text 4
![image](https://user-images.githubusercontent.com/17261190/168477561-a1b8482a-29c9-497c-a354-e9e7a1e2af9a.png)

**Comment by ran-dall** [comment]
I believe these have to do with the tabs and spaces, as opposed to the CRLF and LF, or is everything somewhat related? It seems that the original file was tabbed, and the prettier rules prefer spaces.

**Comment by rchl** [comment]
When I convert the file to use tabs then I see prettier errors in ST:

![Screenshot 2022-05-16 at 23 02 20](https://user-images.githubusercontent.com/153197/168682072-e741c8e7-fa0a-42a2-b4cf-d551f0601645.png)

**Comment by ran-dall** [comment]
@rchl FWIW, I'm using Gentoo Linux with GNOME. So it looks like it defaults to LF for both VSCodium and Sublime; regardless, I don't see the CR symbol on either Sublime or VSCodium.

However, I do get what you get in Sublime, but on mine, it's in VSCodium. Otherwise, I get no output from the Stylelint Sublime LSP.

**Comment by rchl** [comment]
Click this (it's under the `Spaces` label in the status bar) and you should get the same errors in ST.

![Screenshot 2022-05-17 at 13 13 53](https://user-images.githubusercontent.com/153197/168798538-0d716128-0f0f-499c-92bc-0e4a72ef3594.png)

**Comment by ran-dall** [comment]
@rchl Ok, it's currently saved with spaces that don't trigger anything. When I convert to tabs on Sublime (and vscode), I get the errors. So it seems both are aligned. I'll close this.
