### ISSUE TITLE
Autofix on Save not working

### ISSUE THREAD

**Issue by dwhenson** [sublimelsp/LSP-stylelint#31]
Firstly, I love this extension so thanks so much!

I recently upgraded to style lint 14. All was working before, but autofix on save is not working. I have added the setting as per the FAQ, but no joy. I can run it through the command pallet, and it works, but not on automatically on save. Other linters are working (e.g. eslint).

Thanks for any advice.

**Comment by rchl** [comment]
- In the ST console execute the following `sublime.log_commands(True)` and then trigger a document save. What is being printed?

**Comment by dwhenson** [comment]
Looks like this: 

```
command: save {"async": true}
command: js_prettier {"auto_format_prettier_config_path": null, "save_file": true}
command: git_branch_status
```

Is that the correct information to paste?

**Comment by dwhenson** [comment]
That fixed it!

Thank you!!
