### ISSUE TITLE
No linter output

### ISSUE THREAD

**Issue by frothedoatmilk** [sublimelsp/LSP-stylelint#34]
Hello! I just moved over from SublimeLinter-stylelint to using this package. However, after some path troubleshooting, it doesn't seem to be linting my scss files. The troubleshooting page looks normal (server starts, exit code 0), and it is finding my node correctly, but there is no highlighting or reported diagnostics in the panel. It does show `LSP-stylelint` in the gutter, so I'm not super sure what's going on. I have installed the Sass package as per installation instructions, and it has not changed anything.

**Comment by rchl** [comment]
Check those instructions: https://github.com/stylelint/vscode-stylelint#%EF%B8%8F-only-css-and-postcss-are-validated-by-default

Small part of those instructions is vscode-specific but it's easy to figure out the LSP-stylelint equivalent settings change.

**Comment by frothedoatmilk** [comment]
Thank you! Works perfectly now
